repmgr_password: "changeme"
repmgr_db_user_pass: "{{ repmgr_password }}"
repmgrd_service_name: "repmgrd"
repmgrd_service: "/etc/systemd/system/repmgrd.service"
repmgrd_bin: "/usr/lib/postgresql/{{ pg_version }}/bin/repmgrd"
repmgrd_pid: "/var/run/repmgr/repmgrd.pid"
repmgrd_config: "/etc/repmgrd.conf"